#!/usr/bin/env bash

platform=""
stow_target="$HOME"
setup_action="install"

detect_platform() {
	case "$OSTYPE" in
	"linux"*)
		platform="linux"
		;;
	"darwin"*)
		platform="macos"
		;;
	*)
		echo "Unknown platform: $OSTYPE"
		exit 1
	esac

	echo "Detected platform $OSTYPE ($platform)"
	echo
}

dotfiles_find() {
	find . -maxdepth 1 -type d ! -name . | cut -f 2 -d '/'
}

dotfiles_install() {
	while read -r f; do
		echo "[$1] Installing dotfiles for: $f"
		stow -t "$stow_target" -R "$f"
	done < <(dotfiles_find)
}

dotfiles_uninstall() {
	while read -r f; do
		echo "[$1] Uninstalling dotfiles for: $f"
		stow -t "$stow_target" -D "$f"
	done < <(dotfiles_find)
}

dotfiles_setup() {
	if [ ! -d "$1" ]; then
		return 1;
	fi

	pushd "$1" > /dev/null || exit 1
	if [[ "$setup_action" == "install" ]]; then
		dotfiles_install "$1"
	else
		dotfiles_uninstall "$1"
	fi
	popd > /dev/null || exit 1
}

main() {
	if [[ "$1" == "--uninstall" ]]; then
		setup_action="uninstall"
	fi
	detect_platform

	pushd "$(dirname "$(readlink -f "$0")")" > /dev/null || exit 1
	dotfiles_setup "common"
	dotfiles_setup "$platform"
	popd > /dev/null || exit 1
}

main "$@"
