#!/usr/bin/env bash

platform=
stow_target="$HOME"

function detect_platform() {
	case "$OSTYPE" in
	"linux"*)
		platform="linux"
		;;
	"darwin"*)
		platform="macos"
		;;
	*)
		echo "Unknown platform: $OSTYPE"
		exit 1
	esac

	echo "Detected platform $OSTYPE ($platform)"
	echo
}

function install_dotfiles() {
	if [ ! -d "$1" ]; then
		return 1;
	fi

	pushd "$1" > /dev/null
	for f in $(ls -d */ | cut -f 1 -d '/'); do
		echo "[$1] Uninstalling dotfiles for: $f"
		stow -t $stow_target -D $f
	done
	popd > /dev/null
}

function main() {
	detect_platform

	pushd $(dirname "$(readlink -f "$0")") > /dev/null
	install_dotfiles "common"
	install_dotfiles "$platform"
	popd > /dev/null
}

main "$@"
