monitor.alsa.rules = [
    # S/PDIF
    {
        matches = [
            {
                node.name =
                    "alsa_output.usb-Generic_USB_Audio-00.HiFi__SPDIF__sink"
            }
        ]
        actions = {
            update-props = {
                node.disabled = true
            }
        }
    }
]
