#!/usr/bin/env bash

sparse_patterns=("/*" "!README.md" "!LICENSE")

yadm gitconfig core.sparseCheckout true
yadm sparse-checkout set "${sparse_patterns[@]}"

# Ignore everything by default. Adding an item that is currently not tracked
# will require supplying the '-f' flag.
echo "*" >> "$HOME/.local/share/yadm/repo.git/info/exclude"
