# Capture mouse input and allow mouse events to be used as key bindings.
set -g mouse on

# Wait time in milliseconds for tmux to wait after an escape is input
# to determine if it's part of a function or key sequence.
#
# Set to a small non-noticeable amount to remove any felt delay when
# switching modes in vim, but non-zero to avoid broken escape sequences.
set -s escape-time 10

# Use emacs bindings in the tmux command prompt.
set -g status-keys emacs

# Pass through focus events requested from the terminal to applications
# running in tmux.
set -g focus-events on

# Set the amount of time status line messages and other on-screen
# indicators are displayed.
set -g display-time 4000

# Set the maximum number of lines held in window history.
set -g history-limit 100000

# Set the starting index for new windows.
set -g base-index 1

# Set the starting index for new panes.
set -g pane-base-index 1

# When a window is closed, automatically renumber the other windows
# in numerical order.
set -g renumber-windows on

# Set the value of $TERM for new windows.
set -g default-terminal "tmux-256color"

# Append additional features supported by alacritty:
#   - true color
#   - underscore styling
#   - hyperlinks
#   - synchronized output
set -ga terminal-features "alacritty:RGB:usstyle:hyperlinks:sync"

bind r source-file "$HOME/.config/tmux/tmux.conf" \; \
	display -d 750 "config reloaded"

# Color palette.
set -g @bg_main "color235"
set -g @bg_accent "color236"
set -g @bg_highlight "color237"
set -g @fg_main "color248"
set -g @fg_contrast "color255"
set -g @alert "color88"

set -g pane-border-style "fg=#{@bg_highlight},bg=default"
set -g pane-active-border-style "fg=#{@fg_contrast},bg=default"

# Status line.
#
# Enable the status line with a height of one row.
set -g status on

# Redraw the status line every second.
set -g status-interval 1

# Put the window list on the left side of the status line.
set -g status-justify left

set -g status-style "fg=#{@fg_main},bg=#{@bg_main}"
set -g mode-style "fg=#{@fg_main},bg=#{@fg_contrast}"
set -g message-style "fg=#{@fg_contrast},bg=#{@bg_highlight}"
set -g message-command-style "fg=#{@fg_contrast},bg=#{@bg_highlight}"

set -g status-left "#[fg=#{@bg_main},bg=#{@fg_contrast},bold] #S "

set -g window-status-current-style "fg=#{@fg_contrast},bg=#{@bg_highlight},bold"
set -g window-status-bell-style "fg=#{@fg_contrast},bg=#{@alert},bold"

set -g window-status-format " #I:#W#F "
set -g window-status-current-format " #I:#W#F "
set -g window-status-separator ""

set -g status-right "\
#[fg=#{@fg_contrast},bg=#{@bg_accent}] %F \
#[fg=#{@fg_contrast},bg=#{@bg_highlight}] %T \
#[fg=#{@bg_main},bg=#{@fg_contrast},bold] #h "
