# vi: ft=toml
[general]
working_directory = "None"
live_config_reload = true
ipc_socket = true

[window]
decorations = "Full"
opacity = 0.85
title = "Alacritty"
dynamic_title = true

[font]
size = 12

[font.normal]
family = "Cascadia Code"
style = "Medium"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.selection]
background = "#b5d5ff"
text = "#000000"

[colors.normal]
black = "#000000"
blue = "#3465a4"
cyan = "#06989a"
green = "#4e9a06"
magenta = "#75507b"
red = "#cc0000"
white = "#d3d7cf"
yellow = "#c4a000"

[colors.bright]
black = "#555753"
blue = "#729fcf"
cyan = "#34e2e2"
green = "#8ae234"
magenta = "#ad7fa8"
red = "#ef2929"
white = "#eeeeec"
yellow = "#fce94f"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "T",        mods = "Alt",           chars = "\u0002c"           },
    { key = "Key0",     mods = "Alt",           chars = "\u00020"           },
    { key = "Key1",     mods = "Alt",           chars = "\u00021"           },
    { key = "Key2",     mods = "Alt",           chars = "\u00022"           },
    { key = "Key3",     mods = "Alt",           chars = "\u00023"           },
    { key = "Key4",     mods = "Alt",           chars = "\u00024"           },
    { key = "Key5",     mods = "Alt",           chars = "\u00025"           },
    { key = "Key6",     mods = "Alt",           chars = "\u00026"           },
    { key = "Key7",     mods = "Alt",           chars = "\u00027"           },
    { key = "Key8",     mods = "Alt",           chars = "\u00028"           },
    { key = "Key9",     mods = "Alt",           chars = "\u00029"           },
    { key = "Left",     mods = "Alt",           chars = "\u0002p"           },
    { key = "Right",    mods = "Alt",           chars = "\u0002n"           },

    { key = "D",        mods = "Alt",           chars = "\u0002%"           },
    { key = "D",        mods = "Control|Alt",   chars = "\u0002\""          },
    { key = "Space",    mods = "Super",         chars = "\u0002 "           },
    { key = "Up",       mods = "Control|Alt",   chars = "\u0002\u001b[A"    },
    { key = "Down",     mods = "Control|Alt",   chars = "\u0002\u001b[B"    },
    { key = "Right",    mods = "Control|Alt",   chars = "\u0002\u001b[C"    },
    { key = "Left",     mods = "Control|Alt",   chars = "\u0002\u001b[D"    },
    { key = "Up",       mods = "Shift|Alt",     chars = "\u0002\u001b[1;2A" },
    { key = "Down",     mods = "Shift|Alt",     chars = "\u0002\u001b[1;2B" },
    { key = "Right",    mods = "Shift|Alt",     chars = "\u0002\u001b[1;2C" },
    { key = "Left",     mods = "Shift|Alt",     chars = "\u0002\u001b[1;2D" },
]
